on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: Go Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15, 1.16]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test -cover -tags test -race -timeout 30s ./...
